### ISSUE TITLE
Cant install zfc-user with zfc-user-doctrine-mongo-odm

### ISSUE THREAD

**Issue by webologen** [ZF-Commons/ZfcUserDoctrineMongoODM#17]
im getting the error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zf-commons/zfc-user-doctrine-mongo-odm 0.1.1 -> satisfiable by zf-commons/zfc-user-doctrine-mongo-odm[0.1.1].
    - zf-commons/zfc-user-doctrine-mongo-odm 0.1.1 requires doctrine/doctrine-mongo-odm-module 0.8.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by Danielss89** [comment]
Should work now with patch #21
