### ISSUE TITLE
Update composer.json to ZfcUser new version

### ISSUE THREAD

**Issue by benneke10** [ZF-Commons/ZfcUserDoctrineMongoODM#18]
When I was trying to intall ZfcUserDoctrineMongoODM, I noticed that it didn't worked with the latest stable version of ZfcUser (1.2.1). When I let ZfcUserDoctrineMongoODM decide witch version of ZfcUser it needs, it chooses 0.2.2.
Is it possible to update the composer.json so ZfcUserDoctrineMongoODM is also compatible with the latest version of ZfcUser because their are some interesting changes and update's in the latest releases?

**Comment by mdjaman** [comment]
Quite a while! Any date for this update?

**Comment by codeaid** [comment]
Was just about to post the same issue. [ZfcUser](https://github.com/ZF-Commons/ZfcUser/releases) is already v1.2.2. Can't install this module with the latest `ZfcUser` version.

**Comment by Danielss89** [comment]
Fixed in #21
